# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=3000, unique=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mileage', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('first_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('img_link', models.URLField(blank=True, max_length=3000, null=True)),
                ('img_links', models.JSONField(blank=True, default=list, null=True)),
                ('equipment', models.JSONField(blank=True, default=list, null=True)),
                ('organization_phone', models.CharField(blank=True, max_length=300, null=True)),
                ('organization_address', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('hu_until_date', models.DateField(blank=True, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(db_index=True, default='custom', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Retry', 'Retry'), ('OK', 'OK'), ('Error', 'Error')], db_index=True, default='OK', max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
